# Generated by Django 6.0.5 on 2026-05-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_otp_code_order_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('town', 'Recolha na Cidade'), ('door', 'Entrega ao Domicílio')], default='town', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('movitel', 'Movitel (e-Mola)')], default='movitel', max_length=10),
        ),
    ]
