# Generated by Django 4.2.30 on 2026-05-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pin_code_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='otp_resend_count',
        ),
        migrations.AddField(
            model_name='order',
            name='sms_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('town', 'Pickup in City / Town Hub'), ('door', 'Home / Door Delivery')], default='town', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mtn_momo', 'MTN MoMo')], default='mtn_momo', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
